# Copyright 2018, Juniper Networks Pvt Ltd.
# All rights reserved.
# command example: ansible-playbook -i all.inv 02-deploy-networks.yml
---
- name: DEPLOY NETWORKS
  hosts: contrail-ubuntu-vm
  gather_facts: false
  vars:
    openstackrc:
      OS_AUTH_URL: http://keystone-api.openstack:35357/v3
      OS_USERNAME: admin
      OS_PASSWORD: password
      OS_TENANT_NAME: admin
      OS_IDENTITY_API_VERSION: 3
      OS_USER_DOMAIN_NAME: Default
      OS_PROJECT_DOMAIN_NAME: Default
  
  environment: "{{ openstackrc }}"
  
  tasks:
    - name: Import variables from the file /vars/contrail.info into 'info' variable
      include_vars:
        file: contrail.info
        name: info

    - name: Set necessary variables
      set_fact:
        os_auth:
          auth_url: http://keystone-api.openstack:35357/v3
          username: admin
          password: password
          project_name: admin
          project_domain_name: Default
          user_domain_name: Default

    - name: install shade
      pip:
        name: shade

    - name: create scripts directory
      file: state=directory path=~/scripts

    - name: copy the scripts required
      copy:
        src: /root/contrail5.0-automation/Contrail-Install/deploy-networks.yml
        dest: /root/scripts/

    - name: Install networks, subnet, and policy
      os_stack:
        auth: "{{ os_auth }}"
        name: deploy-networks
        state: present
        template: "/root/scripts/deploy-networks.yml"

    - name: sleep for 5 seconds and continue with play
      wait_for: timeout=5

    - name: Gather facts about previously created networks
      shell: openstack network list -f json
      register: network_list
    - name: Display Networks
      set_fact:
        networks: "{{ network_list.stdout | from_json | json_query(jq)}}"
      vars:
        jq: "[?contains(Name,'_network')].{Name:Name,ID:ID,Subnets:Subnets}"
    - debug:
        msg:
          - "{{networks}}"

    - name: Gather facts about previously created subnets
      shell: openstack subnet list -f json
      register: network_list
    - name: Display Subnets
      set_fact:
        subnets: "{{ network_list.stdout | from_json | json_query(jq)}}"
      vars:
        jq: "[?contains(Name,'')].{ID:ID,Network:Network,Subnet:Subnet}"
    - debug:
        msg:
          - "{{subnets}}"

