# Copyright 2018, Juniper Networks Pvt Ltd.
# All rights reserved.
# command example: ansible-playbook -i all.inv 04-image-upload.yml
---
- name: IMAGE UPLOAD
  hosts: contrail-ubuntu-host
  gather_facts: false
  vars:
    openstackrc:
      OS_AUTH_URL: http://keystone-api.openstack:35357/v3
      OS_USERNAME: admin
      OS_PASSWORD: password
      OS_TENANT_NAME: admin
      OS_IDENTITY_API_VERSION: 3
      OS_USER_DOMAIN_NAME: Default
      OS_PROJECT_DOMAIN_NAME: Default
  
  environment: "{{ openstackrc }}"
  tasks:

    - name: Import variables from the file /vars/contrail.info into 'info' variable
      include_vars:
        file: contrail.info
        name: info

    - name: Set necessary variables
      set_fact:
        os_auth:
          auth_url: http://keystone-api.openstack:35357/v3
          username: admin
          password: password
          project_name: admin
          os_tenant_name: admin
          project_domain_name: default
          user_domain_name: default

    - name: download ubuntu gui image
      get_url:
        url: http://releases.ubuntu.com/17.10/ubuntu-17.10.1-desktop-amd64.iso
        dest: /root/images/gui-image.iso

    - name: Upload GUI Image
      os_image:
        name: gui_image
        container_format: bare
        disk_format: vmdk
        filename: /root/images/gui-image.iso
        is_public: yes

    - name: Upload Primary Image 
      os_image:
        auth: "{{ os_auth }}"
        name: webserver-primary_image
        container_format: bare
        disk_format: qcow2
        filename: /root/images/ubuntu-webserver-primary.img
        is_public: yes

    - name: Upload Secondary Image         
      os_image:
        auth: "{{ os_auth }}"
        name: webserver-secondary_image
        container_format: bare
        disk_format: qcow2
        filename: /root/images/ubuntu-webserver-secondary.img
        is_public: yes

    - name: Upload DB Image         
      os_image:
        auth: "{{ os_auth }}"
        name: db_image
        container_format: bare
        disk_format: qcow2
        filename: /root/images/ubuntu-db.img
        is_public: yes

    - name: Gather facts about previously created images
      shell: openstack image list -f json
      register: image_list

    - name: Display Images
      set_fact:
        images: "{{ image_list.stdout | from_json }}"
    - debug:
        msg:
          - "{{images}}"

