# Copyright 2018, Juniper Networks Pvt Ltd.
# All rights reserved.
---
- name: Prepare the centos VM for deployment
  hosts: contrail-ubuntu-vm
  gather_facts: no
  tasks:
    - name: Get epel release
      yum:
        name: epel-release
        state: latest
      
    - name: Get Ansible
      yum:
        name: ansible-2.4.2.0
        state: present
        
    - name: upgrade all packages
      yum: name=* state=latest
      
    - name: sleep for 30 seconds and continue with play
      wait_for: timeout=30
      
    - name: Restart server
      command: /sbin/shutdown -h now
      async: 0
      poll: 0
      ignore_errors: true
      
    - name: Wait for server to restart
      local_action:
        module: wait_for
          port=22
          delay=1
          timeout=600
