# Copyright 2018, Juniper Networks Pvt Ltd.
# All rights reserved.
---
- name: Prepare the centos VM for deployment
  hosts: contrail-ubuntu-vm
  gather_facts: no
  tasks:
    - name: Get epel release
      yum:
        name: epel-release
        state: latest
      
    - name: Get Ansible
      yum:
        name: ansible-2.4.2.0
        state: present
