# Copyright 2018, Juniper Networks Pvt Ltd.
# All rights reserved.
---
- name: Deploy Contrail 5.0 using contrail-ansible-deployer
  hosts: contrail-ubuntu-vm
  gather_facts: false
  tasks:
  - name: Import variables from the file /vars/contrail.info into 'info' variable
    include_vars:
      file: contrail.info
      name: info

  - name: create packages directory
    file: state=directory path=~/packages

  - name: download contrail-ansible-deployer
    get_url:
        url: http://{{ info.contrail_package[0].file_server }}/contrail-ansible-deployer-{{ info.contrail_package[0].contrail_version }}.tar
        dest: ~/packages/contrail-ansible-deployer-{{ info.contrail_package[0].contrail_version }}.tar
        
  - name: Unarchive the contrail-ansible-deployer
    unarchive:
      src: ~/packages/contrail-ansible-deployer-{{ info.contrail_package[0].contrail_version }}.tar
      dest: ~/
      remote_src: yes
      
  - name: parametrized template - a
    template:
      src: ~/Contrail_Automation/templates/bms_aio.j2
      dest: ~/contrail-ansible-deployer/config/instances.yaml

  - name: Install contrail and kolla requirements
    shell: |
    ansible-playbook -i inventory/ playbooks/configure_instances.yml
    args:
      executable: /bin/bash
      chdir: ~/contrail-ansible-deployer
    
  - name: Deploy contrail and kolla containers
    shell: |
    ansible-playbook -i inventory/ -e orchestrator=openstack playbooks/install_contrail.yml
    args:
      executable: /bin/bash
      chdir: ~/contrail-ansible-deployer
