# Copyright 2018, Juniper Networks Pvt Ltd.
# All rights reserved.
---
- name: Post install tasks
  hosts: contrail-ubuntu-vm
  gather_facts: false
  tasks:
  - shell: |
      docker ps|awk '{if(NR>1)print}'|awk '{print $7}'|grep -v "Up"|wc -l
    args:
      executable: /bin/bash
    register: not_running
  - debug:
      var: not_running.stdout_lines

  - fail:
      msg: All pods need to be in running state
    when: not_running.stdout != "0" 
      
  - name: Install gcc
    yum:
      name: gcc
      state: latest
  - name: Install python-devel
    yum:
      name: python-devel
      state: latest
  - name: Install python-openstackclient
    yum:
      name: python-openstackclient
      state: latest
  - name: Install python-ironicclient
    yum:
      name: python-ironicclient
      state: latest
