# Copyright 2018, Juniper Networks Pvt Ltd.
# All rights reserved.
---
- name: Install Openstack client
  hosts: contrail-host
  gather_facts: false
  tasks:
  - name: Install gcc
    yum:
      name: gcc
      state: latest
  - name: Install python-devel
    yum:
      name: python-devel
      state: latest
  - name: Install python-openstackclient
    yum:
      name: python-openstackclient
      state: latest
  - name: Install python-ironicclient
    yum:
      name: python-ironicclient
      state: latest
